
version: '3.1'

services:

  db:
    container_name: mysql-8.3.0
    image: mysql:8.3.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
     - 3308:3306

  adminer:
    container_name: adminer-4.8.1-standalone
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 8080:8080